(part "SBTCJ-13-75+"
    (packageRef "SBTCJ1375")
    (interface
        (port "1" (symbPinId 1) (portName "PORT_1_(180°)_") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NOT_USED") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PORT_2_(0°)_") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "EXT._CAPACITOR_3.6_PF_/EXT._RESISTOR_30.1Ω_/GROUND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SUM_PORT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "SBTCJ-13-75+")
    (property "Description" "RF Power Divider 5 MHz ~ 1 GHz Isolation (Min) 20dB, 1.8 VSWR (Max), 9 Imbalance (Max) 6-SMD, Flat Leads")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/SBTCJ-13-75+.pdf")
    (property "symbolName1" "SBTCJ-13-75+")
)
