(part "VCA820ID"
    (packageRef "SOIC127P600X175-14N")
    (interface
        (port "1" (symbPinId 1) (portName "V+_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VG") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+VIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "+RG") (portType INOUT))
        (port "5" (symbPinId 5) (portName "-RG") (portType INOUT))
        (port "6" (symbPinId 6) (portName "-VIN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "V-_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "V-_2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "VREF") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VOUT") (portType INOUT))
        (port "11" (symbPinId 11) (portName "GND") (portType INOUT))
        (port "12" (symbPinId 12) (portName "I-") (portType INOUT))
        (port "13" (symbPinId 13) (portName "NC") (portType INOUT))
        (port "14" (symbPinId 14) (portName "V+_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-VCA820ID")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/VCA820ID?qs=lqm1LiGWV1%252B%2FxLsKic6RDQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "VCA820ID")
    (property "Description" "150MHz BW with linear in dB gain control variable gain amplifier")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/vca820")
    (property "symbolName1" "VCA820ID")
)
