(part "TPS7A4901DRBT"
    (packageRef "TPS7A4901DRBT")
    (interface
        (port "1" (symbPinId 1) (portName "OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "FB") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "EN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NR/SS") (portType INOUT))
        (port "7" (symbPinId 7) (portName "DNC") (portType INOUT))
        (port "8" (symbPinId 8) (portName "IN") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP_1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "EP_2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "EP_3") (portType INOUT))
        (port "12" (symbPinId 12) (portName "EP_4") (portType INOUT))
        (port "13" (symbPinId 13) (portName "EP_5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS7A4901DRBT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS7A4901DRBT?qs=pV2tVPdcZ6zWH9W1Sn7%252Btg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS7A4901DRBT")
    (property "Description" "LDO Voltage Regulators Vin 3V to 36V 150mA UltraLow Noise")
    (property "Datasheet_Link" "https://www.arrow.com/en/products/tps7a4901drbt/texas-instruments?region=nac")
    (property "symbolName1" "TPS7A4901DRBT")
)
