(part "REC20K-2415DZ"
    (packageRef "REC20K")
    (interface
        (port "1" (symbPinId 1) (portName "+VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-VIN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CTRL") (portType INOUT))
        (port "4" (symbPinId 4) (portName "-VOUT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "COM") (portType INOUT))
        (port "6" (symbPinId 6) (portName "+VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "RECOM Power")
    (property "Manufacturer_Part_Number" "REC20K-2415DZ")
    (property "Description" "20W DC/DC-Converter 'ECONOLINE' 1"x1" 2kV reg 4:1")
    (property "Datasheet_Link" "https://recom-power.com/pdf/Econoline/REC20K-Z.pdf")
    (property "symbolName1" "REC20K-2415DZ")
)
