(part "RDC-20-232-75X+"
    (packageRef "RDC2023275X")
    (interface
        (port "1" (symbPinId 1) (portName "INPUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "COUPLED") (portType INOUT))
        (port "4" (symbPinId 4) (portName "75Ω_TERM_EXTERNAL") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GROUND_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUTPUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "139-RDC-20-232-75X+")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Mini-Circuits/RDC-20-232-75X%2b?qs=ljCeji4nMDlqXNd5I%2FycaA%3D%3D")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "RDC-20-232-75X+")
    (property "Description" "RF Directional Coupler General Purpose 5MHz ~ 2.35GHz 20.2 +/- 1.3dB 1W 6-SMD Module")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/RDC-20-232-75X+.pdf")
    (property "symbolName1" "RDC-20-232-75X+")
)
